#!/bin/sh
#
# /etc/rc.d/init.d/supervisord
# chkconfig: - 64 36
# description: Supervisor Server
# processname: supervisord

# Source init functions
. /etc/rc.d/init.d/functions

prog="supervisord"

prefix="/usr/"
exec_prefix="\$prefix"
prog_bin="\$exec_prefix/bin/supervisord"
PIDFILE="/var/run/\$prog.pid"

start()
{
        echo -n \$"Starting \$prog: "
        daemon \$prog_bin --pidfile \$PIDFILE -c /etc/supervisor/supervisord.conf
        [ -f \$PIDFILE ] && success \$"\$prog startup" || failure \$"\$prog startup"
        echo
}

stop()
{
        echo -n \$"Shutting down \$prog: "
        [ -f \$PIDFILE ] && killproc \$prog || success \$"\$prog shutdown"
        echo
}

case "\$1" in

  start)
    start
  ;;

  stop)
    stop
  ;;

  status)
        status \$prog
  ;;

  restart)
    stop
    start
  ;;

  *)
    echo "Usage: \$0 {start|stop|restart|status}"
  ;;

esac
